name: brainsec
channels:
  - defaults
dependencies:
  - python==3.10.0
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - torchvision
  - pip:
    - torch
    - opencv-python
    - tdqm
    - beautifulsoup4
    - argparse