name: brainsec
channels:
  - defaults
dependencies:
  - python==3.10.0
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - torchvision
  - pip:
    - torch
    - cv2
    - tdqm
    - pylibczi
    - b4s
    - argparse